"""add_s3_settings

Revision ID: 79fe3e192d10
Revises: 20260501_super_timeline
Create Date: 2026-05-06 17:16:44.893308
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '79fe3e192d10'
down_revision = '20260501_super_timeline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attack_chains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('audit_logs_event_id_key'), 'audit_logs', type_='unique')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=True)
    op.alter_column('ioc_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ioc_indicators_ioc_type'), 'ioc_indicators', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_ioc_indicators_value'), 'ioc_indicators', ['value'], unique=False)
    op.alter_column('ioc_matches', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ioc_matches_indicator_id'), 'ioc_matches', ['indicator_id'], unique=False)
    op.alter_column('lateral_movements', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_sigma_hits_processing_job_id'), 'sigma_hits', ['processing_job_id'], unique=False)
    op.alter_column('super_timelines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('system_settings', sa.Column('s3_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('system_settings', sa.Column('s3_endpoint_url', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('s3_access_key', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('s3_secret_key', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('s3_bucket', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('s3_region', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('yara_matches', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yara_matches', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('system_settings', 's3_region')
    op.drop_column('system_settings', 's3_bucket')
    op.drop_column('system_settings', 's3_secret_key')
    op.drop_column('system_settings', 's3_access_key')
    op.drop_column('system_settings', 's3_endpoint_url')
    op.drop_column('system_settings', 's3_enabled')
    op.alter_column('super_timelines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sigma_hits_processing_job_id'), table_name='sigma_hits')
    op.alter_column('lateral_movements', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ioc_matches_indicator_id'), table_name='ioc_matches')
    op.alter_column('ioc_matches', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ioc_indicators_value'), table_name='ioc_indicators')
    op.drop_index(op.f('ix_ioc_indicators_ioc_type'), table_name='ioc_indicators')
    op.alter_column('ioc_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('audit_logs_event_id_key'), 'audit_logs', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attack_chains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
