#!/usr/bin/env bash
# generate-secrets.sh — bootstrap a production .env with strong random secrets.
# Run once before first docker compose up.
set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "[INFO] $ENV_FILE already exists — backing up to ${ENV_FILE}.bak"
  cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

if ! command -v python3 &>/dev/null; then
  echo "[ERROR] python3 is required to generate secrets. Install it and re-run."
  exit 1
fi

gen_secret() {
  python3 -c "import secrets; print(secrets.token_urlsafe(32))"
}

gen_password() {
  python3 -c "
import secrets, string
chars = string.ascii_letters + string.digits
print(''.join(secrets.choice(chars) for _ in range(24)))
"
}

DB_PASSWORD=$(gen_password)
SECRET_KEY=$(gen_secret)
AGENT_SHARED_SECRET=$(gen_secret)
ADMIN_PASSWORD=$(gen_password)
ANALYST_PASSWORD=$(gen_password)
VIEWER_PASSWORD=$(gen_password)

cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/generate-secrets.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# IMPORTANT: Keep this file secret. Never commit it to version control.

# ── Database ──────────────────────────────────────────────────────────────────
POSTGRES_USER=dfir
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=dfir

# ── Security Keys ─────────────────────────────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
AGENT_SHARED_SECRET=${AGENT_SHARED_SECRET}

# ── Auth Settings ─────────────────────────────────────────────────────────────
REQUIRE_AUTH=true
ACCESS_TOKEN_EXPIRE_MINUTES=60

# ── Default User Passwords (change after first login) ─────────────────────────
DFIR_DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
DFIR_DEFAULT_ANALYST_PASSWORD=${ANALYST_PASSWORD}
DFIR_DEFAULT_VIEWER_PASSWORD=${VIEWER_PASSWORD}

# ── CORS / Origins ────────────────────────────────────────────────────────────
ALLOWED_ORIGINS=https://localhost

# ── Frontend API URL (baked into the frontend build) ─────────────────────────
VITE_API_BASE_URL=https://localhost/api/v1

# ── TLS Certificates ─────────────────────────────────────────────────────────
# For local dev: run scripts/generate-self-signed-cert.sh
# For production: replace these with paths to real certificates from your CA or Let's Encrypt
SSL_CERT_PATH=./nginx/certs/cert.pem
SSL_KEY_PATH=./nginx/certs/key.pem

# ── Forensics Tool Paths ──────────────────────────────────────────────────────
EZTOOLS_DIR=/opt/eztools
HAYABUSA_PATH=/opt/hayabusa/hayabusa
CHAINSAW_PATH=/opt/chainsaw/chainsaw
SIGMA_RULES_DIR=/opt/chainsaw/rules/

# ── Demo / Dev ────────────────────────────────────────────────────────────────
SEED_DEMO_DATA=false
EOF

echo ""
echo "[OK] .env written to: $ENV_FILE"
echo ""
echo "  POSTGRES_PASSWORD   = ${DB_PASSWORD:0:8}..."
echo "  SECRET_KEY          = ${SECRET_KEY:0:12}..."
echo "  AGENT_SHARED_SECRET = ${AGENT_SHARED_SECRET:0:12}..."
echo "  ADMIN_PASSWORD      = ${ADMIN_PASSWORD:0:8}..."
echo ""
echo "[NEXT STEP] Generate TLS certificates:"
echo "  bash scripts/generate-self-signed-cert.sh   # local dev (self-signed)"
echo ""
echo "  For production: place real certificates at:"
echo "    nginx/certs/cert.pem"
echo "    nginx/certs/key.pem"
