[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$DemoData,
    [string]$CertificateSubject = "localhost"
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

function New-Secret {
    param([int]$Bytes = 36)
    $buffer = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buffer)
    return ([Convert]::ToBase64String($buffer).TrimEnd("=").Replace("+", "-").Replace("/", "_"))
}

$envFile = Join-Path $projectRoot ".env"
if ((Test-Path $envFile) -and -not $Force) {
    throw ".env already exists. Review it manually, or rerun with -Force to replace it."
}

$postgresPassword = New-Secret
$redisPassword = New-Secret
$secretKey = New-Secret
$agentSecret = New-Secret
$cocKey = New-Secret
$adminPassword = "Dfir-$(New-Secret -Bytes 18)!Aa1"

$values = @{
    DATABASE_URL                    = "postgresql+asyncpg://dfir:$postgresPassword@db:5432/dfir"
    POSTGRES_PASSWORD               = $postgresPassword
    REDIS_PASSWORD                  = $redisPassword
    CELERY_BROKER_URL               = "redis://:$redisPassword@redis:6379/0"
    CELERY_RESULT_BACKEND           = "redis://:$redisPassword@redis:6379/0"
    SECRET_KEY                      = $secretKey
    AGENT_SHARED_SECRET             = $agentSecret
    CHAIN_OF_CUSTODY_SIGNING_KEY    = $cocKey
    DFIR_DEFAULT_ADMIN_PASSWORD     = $adminPassword
    SEED_DEMO_DATA                  = if ($DemoData) { "true" } else { "false" }
}

$updated = Get-Content (Join-Path $projectRoot ".env.example") | ForEach-Object {
    $line = $_
    foreach ($key in $values.Keys) {
        if ($line -match "^$([regex]::Escape($key))=") {
            $line = "$key=$($values[$key])"
            break
        }
    }
    $line
}
$updated += ""
$updated += "# Local TLS files generated by scripts/setup-docker.ps1. Do not commit them."
$updated += "SSL_CERT_PATH=./nginx/certs/cert.pem"
$updated += "SSL_KEY_PATH=./nginx/certs/key.pem"
Set-Content -Path $envFile -Value $updated -Encoding utf8

$certificateDirectory = Join-Path $projectRoot "nginx\certs"
$certificatePath = Join-Path $certificateDirectory "cert.pem"
$keyPath = Join-Path $certificateDirectory "key.pem"
New-Item -ItemType Directory -Force -Path $certificateDirectory | Out-Null

if (-not ((Test-Path $certificatePath) -and (Test-Path $keyPath))) {
    $openssl = Get-Command openssl.exe -ErrorAction SilentlyContinue
    if ($openssl) {
        & $openssl.Source req -x509 -nodes -newkey rsa:4096 -sha256 -days 365 `
            -keyout $keyPath -out $certificatePath -subj "/CN=$CertificateSubject"
    } else {
        # Docker Desktop supplies OpenSSL when it is not installed on Windows.
        & docker run --rm -v "${certificateDirectory}:/certs" alpine:3.20 sh -ec `
            "apk add --no-cache openssl >/dev/null && openssl req -x509 -nodes -newkey rsa:4096 -sha256 -days 365 -keyout /certs/key.pem -out /certs/cert.pem -subj /CN=$CertificateSubject"
    }
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $certificatePath) -or -not (Test-Path $keyPath)) {
        throw "Could not generate local TLS certificate files."
    }
}

Write-Host "Created .env and local TLS files."
if ($DemoData) {
    Write-Host "Demo incident, devices, evidence, detections, and timeline data will be seeded on startup."
}
Write-Host "Initial admin username: admin"
Write-Host "Initial admin password: $adminPassword"
Write-Host "Store this password securely, then start: docker compose up -d --build"
